site_name: Cursus Microcontrollers
site_description: Leer microcontrollers programmeren met Arduino (C++) en MicroPython
site_author: Guy Buys
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
    - scheme: slate
      primary: teal
      accent: orange
nav:
  - Home: index.md
  - Inhoudstabel: inhoud.md
  - Introductie: introductie.md
  - Componenten: componenten.md
  - Bit en Boolean: bit_boolean.md
  - Output: output.md
  - Input: input.md
  - GPIO: gpio.md
  - Datatypes: datatypes.md
  - Je eerste programma: eerste_programma.md
  - Analoog en PWM: analoog_pwm.md
  - SeriÃ«le communicatie: seriele_communicatie.md
  - Toepassingen: toepassingen.md
  - Vooruitblik: vooruitblik.md
markdown_extensions:
  - codehilite
  - admonition
  - toc
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
extra_css:
  - overrides.css
